### ISSUE TITLE
[Contact List] Why is Personal Email a required field?

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#169]
**Describe the bug**
Why is personal email necessary to be a required field?

**Version (please complete the following information):**
 - Version 2.6

**Comment by jhunellbarcenas** [comment]
@charissasylim This is due to no outlook feature. Personal email is used to check if your account/profile in AIDE is associated with it. Thus, will send you a verification code for you to access AIDE. Currently this feature is not available due to network issue's that prevents AIDE to send a verification code to our personal email.

Also, upon my last conversation with Sir Marvin he mentioned that this is due to AIDE's email address is external. It could work if we would have an office email address for AIDE for this feature to work.

**Comment by jhunellbarcenas** [comment]
@charissasylim Can we consider this as close?

**Comment by charissasylim** [comment]
Can we make it optional and then add message when logging in without personal email and outlook

Sent from Yahoo Mail on Android 
 
  On Wed, Aug 28, 2019 at 4:31 PM, jhunellbarcenas<notifications@github.com> wrote:   
@charissasylim Can we consider this as close?

**Comment by charissasylim** [comment]
Make personal email address as not required while there is no working email notification yet.

**Comment by jhunellbarcenas** [comment]
Resolved. Tested in version 3.0.0

**Comment by jhunellbarcenas** [comment]
Still has an issue in sending verification code to external emails.
