### ISSUE TITLE
Was able to login another user in my laptop the same login time was reflected on the application

### ISSUE THREAD

**Issue by vanchsalvador** [rsx-labs/aide-frontend#179]
Scenario: Outlook is NOT Open
I was able to login the other user in the system using their verified email login 
per checking the time is the same as mine (this will be reported as bug) 

**To Reproduce**

Precondition: DO NOT OPEN YOUR OUTLOOK

1. Go to your device 
2. Click on the application
3. Application will require to verify the email add
4. Input the email add (personal) of the user
5. 6 digits code will be displayed 
6. Input the 6 digits > successful login of the user with prompt "welcome c.castillo@ph.fujitsu.com "

**Comment by jhunellbarcenas** [comment]
@vanchsalvador may i know what email address did you try to input? Normally, you should only input the personal email address you have saved in your contacts. If in case you have entered other user's personal email address this scenario will occurs.

This feature supposedly will sent an email that contains the 6 digits code to the personal email address you have saved in your contacts but due to network constrains we just temporarily display the verification code through message box.

**Comment by jhunellbarcenas** [comment]
This is not considered as a bug.

**Comment by jhunellbarcenas** [comment]
@vanchsalvador @charissasylim Can we close this?
