### ISSUE TITLE
[Attendance] Once an employee is shown as present, filed leaves for the same day does not reflect in attendance.

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#207]
**Describe the bug**
Employee is shown as present in attendance for some reason.
SL/VL is filed for the same day.
Attendance still shows employee as present.

**Expected behavior**
Attendance should also consider filed leaves.

**Screenshots**
![image](https://user-images.githubusercontent.com/52391236/64083793-5f865a00-cd57-11e9-827a-5fdc06ba77a9.png)
![image](https://user-images.githubusercontent.com/52391236/64083786-54332e80-cd57-11e9-8cf1-dc89f00583f0.png)

**Version (please complete the following information):**
 - Version 2.6

**Additional context**

**Comment by jhunellbarcenas** [comment]
@charissasylim We may not consider as a bug because the script to file a leaves for employees only works if there is no attendance record for the said date. In this case, Harvey is already marked as present due to his email is used on the AIDE TV. So ideally we do not apply a leave for those employee who are already marked as present.

**Comment by charissasylim** [comment]
Ok make sense.
